language: python
dist: trusty
sudo: required
notifications:
  email: false
services:
- docker
matrix:
  include:
  - python: '2.7'
    env: OS=ubuntu-14.04
  - python: '3.5'
    env: OS=ubuntu-14.04
  - python: '3.6'
    env: OS=ubuntu-14.04
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.6.2
before_install:
- pwd
- bash ci/scripts/travis_docker_setup.sh
- docker version
- docker-compose version
- export DOCKER_IP=127.0.0.1
- docker-compose up -d
- docker ps -a
- docker images
- sudo apt-get install pandoc
- pip install pypandoc
install:
- which python
script:
- python setup.py test
after_success:
- pip install coveralls
- coveralls

before_deploy:
- pip install pypandoc
deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    server: https://testpypi.python.org/pypi
    user: arttii
    password:
      secure: XG3Aa1OD989yHI6XyAkjPsX472JIrpRvYSYZ7tUnVeVE0Db2t0Fpi7hwcPISkEmWvp+XgjBnxdMn+nBvM90bVGvIA7ufJF3owMBPs5H7+/LdjcjGwxrJHqyVPMgH6pd6vJv43E09zqYroihD1BfMD+FQp9j31UNBj7ewrBRRWpgIlXlb8T1diG/CUZqSYFZ8bGJTY1goC/X6IBjvuHsX/tgeeMiko8/WlEcKu0XeBo7uEWByC/rTMqQcZqghc942wnEzUdc9HnNmjOq5QGc2/82o8pUq/xpHA3eXs3/sfFXe4PuorrrL3nBgQeAnUVPbyV7uG2fb2XEPPz0x3T3smP1whReVjPC413uvGryNmP0CPNdlAZXhrTcfc3VYz1hLfC4aCqCdsOCylw9RPYfDdaQDRVc5Wb20+jlvnC1+oXwmv/jcpQ10KDGOgB0iicYM9d3GubZbE+Lxcw9PjuQxD5+0lwHCz4mdI/tjLgngvsgyrwI72Ngq4bFkxkVA3vuMpYJstsclIs7k+xtPc/5GimMpnTTdMyelSqTabb7GF6kOQCLeGIEdDkU9N6vTpnA9ZFt7e/n6Xu5bbvwtLD2WH56PzdF/l8MXj/63Cpi0cS6yNfYrI/1X6LQkLQ+iB7EHh/WSyyXKxMUGkC0sxT8OCly0ZMpgex0sLcj/1eaVf8E=
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: arttii
    password:
      secure: XG3Aa1OD989yHI6XyAkjPsX472JIrpRvYSYZ7tUnVeVE0Db2t0Fpi7hwcPISkEmWvp+XgjBnxdMn+nBvM90bVGvIA7ufJF3owMBPs5H7+/LdjcjGwxrJHqyVPMgH6pd6vJv43E09zqYroihD1BfMD+FQp9j31UNBj7ewrBRRWpgIlXlb8T1diG/CUZqSYFZ8bGJTY1goC/X6IBjvuHsX/tgeeMiko8/WlEcKu0XeBo7uEWByC/rTMqQcZqghc942wnEzUdc9HnNmjOq5QGc2/82o8pUq/xpHA3eXs3/sfFXe4PuorrrL3nBgQeAnUVPbyV7uG2fb2XEPPz0x3T3smP1whReVjPC413uvGryNmP0CPNdlAZXhrTcfc3VYz1hLfC4aCqCdsOCylw9RPYfDdaQDRVc5Wb20+jlvnC1+oXwmv/jcpQ10KDGOgB0iicYM9d3GubZbE+Lxcw9PjuQxD5+0lwHCz4mdI/tjLgngvsgyrwI72Ngq4bFkxkVA3vuMpYJstsclIs7k+xtPc/5GimMpnTTdMyelSqTabb7GF6kOQCLeGIEdDkU9N6vTpnA9ZFt7e/n6Xu5bbvwtLD2WH56PzdF/l8MXj/63Cpi0cS6yNfYrI/1X6LQkLQ+iB7EHh/WSyyXKxMUGkC0sxT8OCly0ZMpgex0sLcj/1eaVf8E=
    on:
      tags: true
      repo: daskos/mentos
      condition: $TRAVIS_PYTHON_VERSION = "2.7"


